"""Train an NRectifiedFlow student that distills a straighter flow from an
already-trained CFM (or NRectifiedFlow) teacher checkpoint.

Reflow needs no real data past the first CFM stage -- it only needs the
teacher's induced noise->data map, generated by integrating the teacher's own
ODE. We still draw batches from the teacher's original dataset each step
purely to size them (NRectifiedFlow.loss ignores their actual content).

Since the student's flow should be straighter than the teacher's, it should
tolerate fewer ODE steps at sample time -- that's the entire point of reflow.
Compare --ode-steps here against the teacher's own --ode-steps to see if it
held up with fewer.

Example:
    uv run python scripts/train.py --framework cfm --steps 100000 --name teacher
    uv run python scripts/reflow.py outputs/runs/teacher --steps 50000 --ode-steps 8
"""

import argparse
import json
from argparse import Namespace
from pathlib import Path

import numpy as np
import torch

from frameworks.cfm import CFM, ReFlow
from models.mlp import FlowMLP
from scripts.train import build_dataset
from utils.normalize import from_model_space
from utils.device import preferred_device
from utils.report import evaluate_and_plot
from utils.trainer import train


def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "teacher",
        type=Path,
        help="teacher run directory or model.pt "
        "(must be trained with --framework cfm)",
    )
    p.add_argument(
        "--gen-steps",
        type=int,
        default=50,
        help="ODE steps used to integrate the teacher when generating pairs",
    )
    p.add_argument(
        "--ode-steps",
        type=int,
        default=10,
        help="ODE steps for the student at evaluation -- try fewer than "
        "the teacher used, that's the point of reflow",
    )
    p.add_argument("--steps", type=int, default=20000)
    p.add_argument("--batch-size", type=int, default=256)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--log-every", type=int, default=1000)
    p.add_argument("--n-samples", type=int, default=20000)
    p.add_argument("--name", default=None)
    p.add_argument("--outdir", type=Path, default=Path("outputs/runs"))
    p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def load_teacher(path: Path):
    ckpt_path = path / "model.pt" if path.is_dir() else path
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    targs = Namespace(**ckpt["args"])
    if getattr(targs, "framework", "ddpm") != "cfm":
        raise ValueError(
            f"reflow needs a CFM-trained teacher (scripts/train.py --framework cfm), "
            f"got framework={getattr(targs, 'framework', None)!r}"
        )

    model = FlowMLP(
        dim=targs.board_dim,
        hidden_dim=targs.hidden_dim,
        time_emb_dim=targs.time_emb_dim,
        num_features=targs.num_features,
        num_harmonics=targs.num_harmonics,
        depth=targs.depth,
        n_tiles=targs.n_tiles,
        use_rff=targs.use_rff,
    )
    model.load_state_dict(ckpt["model"])
    model.eval()
    return model, targs, ckpt_path.parent


def build_student(targs):
    return FlowMLP(
        dim=targs.board_dim,
        hidden_dim=targs.hidden_dim,
        time_emb_dim=targs.time_emb_dim,
        num_features=targs.num_features,
        num_harmonics=targs.num_harmonics,
        depth=targs.depth,
        n_tiles=targs.n_tiles,
        use_rff=targs.use_rff,
    )


def main():
    args = parse_args()
    teacher_model, targs, teacher_dir = load_teacher(args.teacher)
    device = preferred_device()
    teacher_model.to(device)
    teacher = CFM()

    name = (
        args.name
        or f"reflow_{teacher_dir.name}_gen{args.gen_steps}_steps{args.steps}_seed{args.seed}"
    )
    rundir = args.outdir / name
    rundir.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(args.seed)
    rng = np.random.default_rng(args.seed)

    # only used to size each training batch -- ReFlow.loss ignores content
    dataset = build_dataset(targs)
    student = build_student(targs).to(device)
    nrf = ReFlow(teacher, teacher_model, num_gen_steps=args.gen_steps)

    print(f"reflow run: {name}")
    print(f"  teacher: {teacher_dir} (gen_steps={args.gen_steps})")
    print(f"  student params={sum(p.numel() for p in student.parameters())}")
    print(f"  device={device}")

    train(
        student,
        nrf,
        dataset,
        num_steps=args.steps,
        batch_size=args.batch_size,
        lr=args.lr,
        log_every=args.log_every,
        rng=rng,
    )

    student.eval()
    generated = from_model_space(
        nrf.sample(student, n=args.n_samples, num_steps=args.ode_steps)
    ).numpy()
    ground_truth = dataset.sample(args.n_samples, rng)

    metrics = evaluate_and_plot(
        generated,
        ground_truth,
        targs.board_dim,
        targs.n_tiles,
        rundir,
        desc=f"student, {args.ode_steps} ODE steps",
        label="reflow samples",
    )

    save_args = dict(vars(targs))
    save_args.update(
        teacher=str(teacher_dir), gen_steps=args.gen_steps, ode_steps=args.ode_steps
    )
    torch.save({"model": student.state_dict(), "args": save_args}, rundir / "model.pt")
    (rundir / "metrics.json").write_text(
        json.dumps(
            {"name": name, "teacher": str(teacher_dir), "metrics": metrics}, indent=2
        )
    )
    print(f"\nwrote {rundir}/")


if __name__ == "__main__":
    main()
